# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    # Docs are always built on Python 3.12. See also the tox config.
    python: "3.12"
  jobs:
    pre_install:
      - pip install mkdocs-material
#    pre_build:
#      - tox -e docs-lint
    build:
      html:
        - python -m mkdocs build --config-file docs/locales/mkdocs.fr.yml --site-dir $READTHEDOCS_OUTPUT/html/
#        - python -m mkdocs build -f mkdocs.yml -d $READTHEDOCS_OUTPUT/html/

# Build documentation in the docs/ directory with MkDocs
mkdocs:
 configuration: mkdocs.yml

# Build docs as PDF (other options are epub and htmlzip)
#formats:
#   - pdf

# Optionally declare the Python requirements required to build your docs
python:
  install:
  - method: pip
    path: .
    extra_requirements:
      - docs
