# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: BeeWare Tutorial
site_url: https://docs.beeware.org/

docs_dir:
  docs

exclude_docs:
  toga
  overrides

not_in_nav: |
  /index.md

theme:
  name: material
  features:
    - content.tabs.link
    - toc.follow
    - navigation.path
    - content.code.copy
    - navigation.indexes
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.blocks.admonition
  - pymdownx.caret
  - pymdownx.blocks.tab:
      alternate_style: true
  - toc:
      permalink: true
      title: On this page

extra:
  "beta_support": ^&beta;^
  "not_supported": ^&#x274C;^
  "beta": ○
  "stable": ●
  alternate:
    - name: English
      lang: en
    - name: Français
      link: /fr/
      lang: fr
    - name: Español
      link: /es/
      lang: es

plugins:
  - search
  - autorefs
  - include-markdown
  - literate-nav:
      nav_file: SUMMARY.md
  - macros:
      j2_comment_start_string: '[#'  # Set temporarily to deal with title anchors
      j2_comment_end_string: '#]'  # Set temporarily to deal with title anchors
  - table-reader
  - spellcheck:
      backends:
        - codespell:
            dictionaries: [clear]
      known_words: spelling_wordlist
      ignore_code: yes
