INHERIT: config.yml
site_name: BeeWare Tutorial
site_url: https://docs.beeware.org/fr
docs_dir: /home/docs/checkouts/readthedocs.org/user_builds/tutorial-mkdocs-test-fr/checkouts/latest/fr

theme:
  language: fr
